# Site settings
title: Nadafancy.com
email: luisg@nadafancy.com
description: > # this means to ignore newlines until "baseurl:"
  El blog personal de Pipe Gutierre
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Dudemullet
github_username: Dudemullet

# Build settings
markdown: kramdown
