name: Nadafancy
description: Venimos a aprender
meta_description: "Blog de programacion creado por Luis Felipe Gutierrez,  @Dudemullet"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.nadafancy.com'
google_analytics: 'UA-49913035-1'

# Author social links
twitter_username: Dudemullet
github_username: Dudemullet

# Details for the RSS feed generator
url:            http://blog.nadafancy.com
author:         Luis Gutierrez

prose:
  rooturl: '_posts'
  siteurl: 'http://blog.nadafancy.com'
  media: 'assets/images'
