name: Nadafancy
description: Nothingfancy
meta_description: "Blog de programacion creado por Luis Felipe Gutierrez,  @Dudemullet"

markdown: kramdown
logo: false
paginate: 15
baseurl: /
domain_name: 'http://nadafancy.com'
google_analytics: 'UA-49913035-1'

# Author social links
twitter_username: Dudemullet
github_username: Dudemullet

# Details for the RSS feed generator
url:            http://nadafancy.com
author:         Luis Gutierrez

prose:
  rooturl: '_posts'
  siteurl: 'http://nadafancy.com'
  media: 'assets/images'
post:
  template: '_templates/post.html'
  extension: 'md'
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
